### ISSUE TITLE
Colors messed up in 2022.1 (but that might be 2022.1)

### ISSUE THREAD

**Issue by ForsakenHarmony** [subtheme-dev/monokai-pro#31]
**Describe the bug**
Most variants are very messed up in 2022.1, switching to a light theme and back also breaks things even more (which makes me think 2022.1 might just be broken, it's EAP)

**To Reproduce**
1. Use 2022.1
2. ??
3. It's broken

**Screenshots**
Monokai Pro (Filter Spectrum)
![](https://i.hrmny.sh/Nd9DJkMue1.png)

**Application:**
GoLand, CLion

**Comment by nicholasq** [comment]
The font is black for me which makes the text almost unreadable and this plugin unusable. I am also on intellij IDEA 2022.1

**Comment by espositocode** [comment]
Ok, I see the issue on 2022. Not sure what the issue is yet, but I'm guessing a color field is deprecated. I'll take a look.

**Comment by ForsakenHarmony** [comment]
Just got an error about colors as well, maybe it's helpful.

<details>
<summary>Stacktrace</summary>

```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'c' of com/intellij/ui/ColorUtil.isDark must not be null
	at com.intellij.ui.ColorUtil.$$$reportNull$$$0(ColorUtil.java)
	at com.intellij.ui.ColorUtil.isDark(ColorUtil.java)
	at com.intellij.ide.ui.laf.LafManagerImpl$DefaultMenuArrowIcon.lambda$static$0(LafManagerImpl.java:1208)
	at com.intellij.ide.ui.laf.LafManagerImpl$DefaultMenuArrowIcon.lambda$new$2(LafManagerImpl.java:1212)
	at com.intellij.ide.ui.laf.MenuArrowIcon.paintIcon(MenuArrowIcon.kt:18)
	at com.intellij.ui.plaf.beg.IdeaMenuUI.paint(IdeaMenuUI.java:171)
	at com.intellij.ui.plaf.beg.IdeaMenuUI.update(IdeaMenuUI.java:414)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:800)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1077)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5263)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1654)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1629)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1566)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1333)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5211)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5021)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:868)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:851)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:851)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:826)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:775)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1901)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:479)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

</details>

**Comment by GMatrixGames** [comment]
Any updates on this?

**Comment by ben-sellar** [comment]
2022.1 is now released, any chance of an update?

**Comment by espositocode** [comment]
Sorry guys, I have not had time to look at this yet. I'm going to sit down with this tonight after work. I'll post an update if I make progress.

**Comment by espositocode** [comment]
Turns out that 2022 requires the hash symbol before hex values now. I pushed the update to the plugin repo, but if anybody can test this out before approval, I would appreciate it: https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/167601

FYI, I noticed I had to restart JetBrains to get all of the changes to register. Clicking around, things seem to appear normal.

**Comment by GMatrixGames** [comment]
It appears Filter Spectrum is still bugged
![image](https://user-images.githubusercontent.com/25112532/163076808-d1a067db-ae88-4a80-a97d-cb03b4136d0e.png)

**Comment by espositocode** [comment]
Ah dang it, I only updated the default colors. Thanks for pointing this out.

The default colors look ok to you?

**Comment by GMatrixGames** [comment]
Default colors look good.

**Comment by GMatrixGames** [comment]
It appears colors work great for Spectrum when they're given the pound symbol
![image](https://user-images.githubusercontent.com/25112532/163090030-4e820cc4-fd6a-40a9-8380-1bd4e5346812.png)

**Comment by espositocode** [comment]
Unfortunately they approved my last build very quickly, but 1.8.1 is pending: https://plugins.jetbrains.com/plugin/13643-monokai-pro-theme/versions/stable/167801
